Ext.require(['Ext.data.*']);

Ext.onReady(function() {
	var store = Ext.create('Ext.data.JsonStore', {
    fields: ['name', 'data'],
    data: [{"Date":"2012-12-04","Volunteer 1":"Jeff Schell","Volunteer 2":null,"Start Time":"01:08:34","End Time":"","Resting Leisure":1,"Active or Sporting Leisure":1,"Walking or Running":1,"Picnic or Grilling":0,"Domestic Animals":1,"Surfing or Swimming":1,"ACTIVE Shore Fishing":1,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":1,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":1,"Litter":0},
{"Date":"2012-12-04","Volunteer 1":"Sally Do","Volunteer 2":null,"Start Time":"01:25:02","End Time":"","Resting Leisure":3,"Active or Sporting Leisure":15,"Walking or Running":1,"Picnic or Grilling":1,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-04","Volunteer 1":"Sally Do","Volunteer 2":null,"Start Time":"01:25:33","End Time":"","Resting Leisure":15,"Active or Sporting Leisure":1,"Walking or Running":1,"Picnic or Grilling":1,"Domestic Animals":4,"Surfing or Swimming":95,"ACTIVE Shore Fishing":14,"Recreational Boating":2,"Commercial Boating":16,"ACTIVE Commercial Boating":8,"ACTIVE Recreational Boat Fishing":1,"Diving":1,"Kelp Harvesting":1,"Runoff":1,"Open Dumpster":1,"Cigarette Butts":1,"Animal Droppings":1,"Litter":1},
{"Date":"2012-12-04","Volunteer 1":"Sharon Chung","Volunteer 2":null,"Start Time":"02:21:09","End Time":"","Resting Leisure":null,"Active or Sporting Leisure":null,"Walking or Running":null,"Picnic or Grilling":null,"Domestic Animals":null,"Surfing or Swimming":null,"ACTIVE Shore Fishing":null,"Recreational Boating":null,"Commercial Boating":null,"ACTIVE Commercial Boating":null,"ACTIVE Recreational Boat Fishing":null,"Diving":null,"Kelp Harvesting":null,"Runoff":null,"Open Dumpster":null,"Cigarette Butts":null,"Animal Droppings":null,"Litter":null},
{"Date":"2012-12-04","Volunteer 1":"Sharon Chung","Volunteer 2":null,"Start Time":"02:40:05","End Time":"","Resting Leisure":null,"Active or Sporting Leisure":null,"Walking or Running":null,"Picnic or Grilling":null,"Domestic Animals":null,"Surfing or Swimming":null,"ACTIVE Shore Fishing":null,"Recreational Boating":null,"Commercial Boating":null,"ACTIVE Commercial Boating":null,"ACTIVE Recreational Boat Fishing":null,"Diving":null,"Kelp Harvesting":null,"Runoff":null,"Open Dumpster":null,"Cigarette Butts":null,"Animal Droppings":null,"Litter":null},
{"Date":"2012-12-04","Volunteer 1":"Sharon Chung","Volunteer 2":null,"Start Time":"02:41:48","End Time":"","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":1,"Cigarette Butts":1,"Animal Droppings":1,"Litter":1},
{"Date":"2012-12-04","Volunteer 1":"Jeff Schell","Volunteer 2":null,"Start Time":"08:41:47","End Time":"","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-05","Volunteer 1":"Sharon Chung","Volunteer 2":null,"Start Time":"00:46:04","End Time":"00:46:32","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-05","Volunteer 1":"Sharon Chung","Volunteer 2":null,"Start Time":"00:54:15","End Time":"","Resting Leisure":null,"Active or Sporting Leisure":null,"Walking or Running":null,"Picnic or Grilling":null,"Domestic Animals":null,"Surfing or Swimming":null,"ACTIVE Shore Fishing":null,"Recreational Boating":null,"Commercial Boating":null,"ACTIVE Commercial Boating":null,"ACTIVE Recreational Boat Fishing":null,"Diving":null,"Kelp Harvesting":null,"Runoff":null,"Open Dumpster":null,"Cigarette Butts":null,"Animal Droppings":null,"Litter":null},
{"Date":"2012-12-05","Volunteer 1":"Matt Murbach","Volunteer 2":null,"Start Time":"17:06:15","End Time":"17:13:29","Resting Leisure":3,"Active or Sporting Leisure":0,"Walking or Running":5,"Picnic or Grilling":4,"Domestic Animals":3,"Surfing or Swimming":4,"ACTIVE Shore Fishing":1,"Recreational Boating":4,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":5,"Diving":0,"Kelp Harvesting":0,"Runoff":3,"Open Dumpster":0,"Cigarette Butts":2,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-11","Volunteer 1":"Coastkeeper SD","Volunteer 2":null,"Start Time":"13:00:44","End Time":"13:01:19","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-17","Volunteer 1":"Coastkeeper SD","Volunteer 2":null,"Start Time":"17:24:04","End Time":"","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2012-12-18","Volunteer 1":"Coastkeeper SD","Volunteer 2":"Coastkeeper SD","Start Time":"15:47:42","End Time":"","Resting Leisure":null,"Active or Sporting Leisure":null,"Walking or Running":null,"Picnic or Grilling":null,"Domestic Animals":null,"Surfing or Swimming":null,"ACTIVE Shore Fishing":null,"Recreational Boating":null,"Commercial Boating":null,"ACTIVE Commercial Boating":null,"ACTIVE Recreational Boat Fishing":null,"Diving":null,"Kelp Harvesting":null,"Runoff":null,"Open Dumpster":null,"Cigarette Butts":null,"Animal Droppings":null,"Litter":null},
{"Date":"2012-12-29","Volunteer 1":"Matt Murbach","Volunteer 2":null,"Start Time":"16:23:49","End Time":"16:24:15","Resting Leisure":14,"Active or Sporting Leisure":3,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":0,"ACTIVE Shore Fishing":0,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0},
{"Date":"2013-01-09","Volunteer 1":"David Drabik","Volunteer 2":null,"Start Time":"17:40:55","End Time":"17:41:13","Resting Leisure":0,"Active or Sporting Leisure":0,"Walking or Running":0,"Picnic or Grilling":0,"Domestic Animals":0,"Surfing or Swimming":1,"ACTIVE Shore Fishing":7,"Recreational Boating":0,"Commercial Boating":0,"ACTIVE Commercial Boating":0,"ACTIVE Recreational Boat Fishing":0,"Diving":0,"Kelp Harvesting":0,"Runoff":0,"Open Dumpster":0,"Cigarette Butts":0,"Animal Droppings":0,"Litter":0}]
});
    
    
    
});